pipeline:
  name: Java-CI
  identifier: Java_CI
  projectIdentifier: default_project
  orgIdentifier: default

  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI

        spec:
          cloneCodebase: true

          infrastructure:
            useFromStage: false

            type: KubernetesDirect

            spec:
              connectorRef: account.harnessImage
              namespace: default

              type: KubernetesDirect

              spec:
                platform: Linux

              automountServiceAccountToken: true

          execution:
            steps:
              - step:
                  type: Run
                  name: Maven_Build
                  identifier: Maven_Build

                  spec:
                    shell: Sh

                    command: |
                      mvn clean package
