pipeline:
  name: Java-CI
  identifier: Java_CI
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}

  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI

        spec:
          cloneCodebase: true

          infrastructure:
            type: Cloud
            spec: {}

          execution:
            steps:
              - step:
                  type: Run
                  name: Maven_Build
                  identifier: Maven_Build
                  spec:
                    shell: Sh
                    command: |
                      mvn clean package

        variables: []
